#!/bin/sh

set -e
set -x

####################################################################################

if [ -f ./sde-ci-common ] ; then
    . ./sde-ci-common
elif [ -f devel-tools/sde-ci-common ] ; then
    . devel-tools/sde-ci-common
else
    . sde-ci-common
fi

####################################################################################

case "$1" in
    before_install)
        install_common_dependencies
    ;;
    build)
        shift
        test "x-$TRAVIS" = x-true || exit 1

        export PROJECT_DIR="$TRAVIS_BUILD_DIR/project-dir"
        export INSTALL_DIR="$TRAVIS_BUILD_DIR/project-dir-install"
        export SHARED_PREFIX="$TRAVIS_BUILD_DIR/project-dir-install/shared-root"
        export ENSURE_CLEAN_BUILD=y

        export PROJECTS="$1"

        if [ -d "$TRAVIS_BUILD_DIR/.git" ] ; then
            export PREFETCHED_PROJECT="$1"
            export PREFETCHED_PROJECT_PATH="$TRAVIS_BUILD_DIR"
        fi

        export PATH="$TRAVIS_BUILD_DIR/project-dir/devel-tools:$PATH"

        sde-ci-build
    ;;
esac
