#!/bin/sh

####################################################################################

if [ "`id -u`" = "0" ] ; then
    SUDO=
else
    SUDO=sudo
fi

####################################################################################

PRETTY_NAME=
NAME=
VERSION_ID=
VERSION=
ID=
ID_LIKE=

if [ -f /etc/os-release ] ; then
    . /etc/os-release
elif [ -f /usr/lib/os-release ] ; then
    . /usr/lib/os-release
elif which -s freebsd-version ; then
    PRETTY_NAME="FreeBSD"
    NAME="FreeBSD"
    VERSION_ID="`freebsd-version`"
    VERSION="`freebsd-version`"
    ID="freebsd"
    ID_LIKE="freebsd"
fi

export OS_PRETTY_NAME="${PRETTY_NAME:-unknown}"
export OS_NAME="${NAME:-unknown}"
export OS_VERSION_ID="${VERSION_ID:-unknown}"
export OS_VERSION="${VERSION:-unknown}"
export OS_ID="${ID:-unknown}"
export OS_ID_LIKE="${ID_LIKE:-unknown}"

####################################################################################

repos_updated=n
update_repos() {
    if [ "x-$repos_updated" = "x-y" ] ; then
        return 0
    fi

    case "$OS_ID" in
        debian | ubuntu)
            $SUDO apt-get -qq update
        ;;
        centos)
            #$SUDO yum -y update
            :
        ;;
        arch)
            $SUDO pacman -Syq
        ;;
        freebsd)
            $SUDO pkg update
        ;;
        *)
            echo "unknown OS_ID: $OS_ID"
            return 1
        ;;
    esac

    repos_updated=y
    return 0
}

install_package() {
    update_repos

    local package_name="`fix_package_name "$1"`"

    case "$OS_ID" in
        debian | ubuntu)
            $SUDO apt-get install -q -y --no-install-recommends $package_name
        ;;
        centos)
            $SUDO yum -q -y install $package_name
        ;;
        arch)
            $SUDO pacman -Sq --noconfirm $package_name
        ;;
        freebsd)
            $SUDO pkg install -y $package_name
        ;;
        *)
            echo "unknown OS_ID: $OS_ID"
            return 1
        ;;
    esac

}

install_package_for_command() {
    if ! which "$2" 1>/dev/null 2>/dev/null ; then
        install_package "$1"
    fi
}

fix_package_name() {
    local package_name="$1"

    case "${OS_ID}-${OS_VERSION_ID}" in
        ubuntu-12.04)
            case "$package_name" in
                libmenu-cache-dev) package_name=libmenu-cache1-dev ;;
            esac
        ;;
        centos-7)
            case "$package_name" in
                libmenu-cache-dev) package_name=menu-cache-devel ;;
                libgtk2.0-dev) package_name=gtk2-devel ;;
                libjansson-dev) package_name=jansson-devel ;;
                gtk-doc-tools) package_name=gtk-doc ;;
            esac
        ;;
        arch-unknown)
            case "$package_name" in
                libmenu-cache-dev) package_name=menu-cache ;;
                libgtk2.0-dev) package_name=gtk2 ;;
                libjansson-dev) package_name=jansson ;;
                libgtop2-dev) package_name=libgtop2 ;;
                libxml2-dev) package_name=libxml2 ;;
                g++) package_name=gcc ;;
                gtk-doc-tools) package_name=gtk-doc ;;
                autopoint) package_name=gettext ;;
            esac
        ;;
        freebsd-*)
            case "$package_name" in
                libmenu-cache-dev) package_name=menu-cache ;;
                libgtk2.0-dev) package_name=gtk2 ;;
                libjansson-dev) package_name=jansson ;;
                gtk-doc-tools) package_name=gtk-doc ;;
                autopoint) package_name=gettext ;;
                make) package_name=gmake ;;
            esac
        ;;
    esac

    echo "$package_name"
}

####################################################################################

prepare_devel_environment() {
    install_package git
    install_package gcc g++
    install_package make
    install_package automake
    install_package autoconf
    install_package gettext
    install_package autopoint
    install_package curl
}

####################################################################################

install_common_dependencies() {

    case "${OS_ID}-${OS_VERSION_ID}" in
        centos-7)
            install_package epel-release
        ;;
    esac

    install_package libmenu-cache-dev
    install_package libgtk2.0-dev
    install_package libjansson-dev
    install_package libgtop2-dev         # for waterline-plugin-multiload
    install_package libxml2-dev          # for qk
    install_package txt2tags             # for qk
    install_package_for_command intltool intltoolize
    install_package_for_command gtk-doc-tools gtkdocize
}

####################################################################################

