#!/bin/sh

set -e
set -x

####################################################################################

repos_updated=n
update_repos() {
    if [ "x-$repos_updated" != "x-y" ] ; then
        sudo apt-get -qq update
        repos_updated=y
    fi
}

install_package() {
    update_repos
    sudo apt-get install -y "$1"
}

install_package_for_command() {
    if ! which "$2" 1>/dev/null 2>/dev/null ; then
        update_repos
        sudo apt-get install -y "$1"
    fi
}

####################################################################################

case "$1" in
    before_install)
        install_package libmenu-cache-dev
        install_package libgtk2.0-dev
        install_package libjansson-dev
        install_package_for_command intltool intltoolize
        install_package_for_command gtk-doc-tools gtkdocize
    ;;
    build)
        shift
        test "x-$TRAVIS" = x-true || exit 1

        export PROJECT_DIR="$TRAVIS_BUILD_DIR/project-dir"
        export INSTALL_DIR="$TRAVIS_BUILD_DIR/project-dir-install"
        export SHARED_PREFIX="$TRAVIS_BUILD_DIR/project-dir-install/shared-root"
        export ENSURE_CLEAN_BUILD=y

        export PROJECTS="$1"

        if [ -d "$TRAVIS_BUILD_DIR/.git" ] ; then
            export PREFETCHED_PROJECT="$1"
            export PREFETCHED_PROJECT_PATH="$TRAVIS_BUILD_DIR"
        fi

        export PATH="$TRAVIS_BUILD_DIR/project-dir/devel-tools:$PATH"

        sde-ci-build
    ;;
esac
